import "./globals.css";
import { Josefin_Sans } from "next/font/google";

const josefineSans = Josefin_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "600"],
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${josefineSans.className}`}>
      <body>{children}</body>
    </html>
  );
}
